/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module 'sst' {
  export interface Resource {
    AppDB: {
      clusterArn: string
      database: string
      host: string
      password: string
      port: number
      reader: string
      secretArn: string
      type: 'sst.aws.Aurora'
      username: string
    }
    AppService: {
      name: string
      type: 'sst.aws.Function'
      url: string
    }
    AppVPC: {
      type: 'sst.aws.Vpc'
    }
    AppWeb: {
      type: 'sst.aws.StaticSite'
      url: string
    }
    BETTER_AUTH_SECRET: {
      type: 'sst.sst.Secret'
      value: string
    }
    CMC_API_KEY: {
      type: 'sst.sst.Secret'
      value: string
    }
    CRYPTOCOMPARE_API_KEY: {
      type: 'sst.sst.Secret'
      value: string
    }
    DatabaseMigrator: {
      name: string
      type: 'sst.aws.Function'
    }
    MOBULA_API_KEY: {
      type: 'sst.sst.Secret'
      value: string
    }
    Router: {
      type: 'sst.aws.Router'
      url: string
    }
    SMTP_PASSWORD: {
      type: 'sst.sst.Secret'
      value: string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst'
export {}
