/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module 'sst' {
  export interface Resource {
    BETTER_AUTH_SECRET: {
      type: 'sst.sst.Secret'
      value: string
    }
    BTCDB: {
      clusterArn: string
      database: string
      host: string
      password: string
      port: number
      reader: string
      secretArn: string
      type: 'sst.aws.Aurora'
      username: string
    }
    BTCService: {
      service: string
      type: 'sst.aws.Service'
      url: string
    }
    BTCVPC: {
      type: 'sst.aws.Vpc'
    }
    BTCWeb: {
      type: 'sst.aws.StaticSite'
      url: string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst'
export {}
